# Generated by Django 5.1.1 on 2024-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domainname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'domainname', 'country')},
        ),
    ]
