# Generated by Django 5.1.1 on 2024-09-18 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailapp', '0002_alter_company_domainname_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='softdelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailformat',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='emailformat',
            name='softdelete',
            field=models.IntegerField(default=0),
        ),
    ]
