# Generated by Django 5.1.4 on 2025-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailapp', '0003_company_date_company_softdelete_emailformat_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(default='', max_length=15)),
                ('designation', models.CharField(default='', max_length=15)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
